openapi: 3.0.3
info:
  title: Carbon Intensity API
  description: API for getting carbon intensity data.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /carbon-intensity/{zone}:
    get:
      summary: Get carbon intensity data by zone
      security:
        - BearerAuth: []
      tags:
        - Carbon Intensity
      parameters:
        - name: zone
          in: path
          required: true
          schema:
            type: string
          description: The zone for which to get carbon intensity data (e.g. DE, TH, US-NY-NYIS).
      responses:
<<<<<<< HEAD
        "200":
=======
        '200':
>>>>>>> origin
          description: Carbon intensity data
          content:
            application/json:
              schema:
                type: object
                properties:
                  zone:
                    type: string
                    description: The zone for which the data is provided.
                    example: DE
                  carbonIntensity:
                    type: number
                    description: The carbon intensity value.
                    example: 140
<<<<<<< HEAD
=======
<<<<<<< HEAD

        "404":
          description: Zone not found
        "500":
          description: Internal server error
  /carbon-intensity/zones:
    get:
      summary: Get list of available zones
      security:
        - BearerAuth: []
      tags:
        - Carbon Intensity
      responses:
        "200":
          description: List of available zones
          content:
            application/json:
              schema:
                type: object
                properties:
                  zones:
                    type: array
                    items:
                      type: string
                    example: ["DE", "US-NY-NYIS", "TH"]
        "500":
          description: Internal server error
=======
                  
>>>>>>> origin
        '404':
          description: Zone not found
        '500':
          description: Internal server error
<<<<<<< HEAD
  /carbon-intensity/zones:
    get:
      summary: Get list of available zones
      security:
        - BearerAuth: []
      tags:
        - Carbon Intensity
      responses:
        '200':
          description: List of available zones
          content:
            application/json:
              schema:
                type: object
                properties:
                  zones:
                    type: array
                    items:
                      type: string
                    example: ["DE", "US-NY-NYIS", "TH"]
        '500':
          description: Internal server error
=======

>>>>>>> origin
>>>>>>> origin
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
<<<<<<< HEAD
      bearerFormat: JWT
=======
      bearerFormat: JWT
  schemas:
    CarbonIntensityData:
      type: object
      required:
        - zone
        - carbonIntensity
<<<<<<< HEAD
=======
        - datetime
        - updatedAt
        - createdAt
>>>>>>> origin
      properties:
        zone:
          type: string
          example: DE
        carbonIntensity:
          type: number
          example: 140
<<<<<<< HEAD
=======
          
>>>>>>> origin
>>>>>>> origin
