openapi: 3.1.0
info:
  title: Worker Gateway API
  version: 1.0.0
  description: API for communication between Worker Registry, Worker Daemon und Job-Service.

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /run-job:
    post:
      summary: Submits job to Worker Gateway for execution by Worker Daemon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId:
                  type: string
                workerId:
                  type: string
              required: [jobId, workerId]
      responses:
        '202':
          description: Job wurde angenommen und wird verarbeitet

  /result:
    post:
      summary: Result of a job processed by the worker daemon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId:
                  type: string
                status:
                  type: string
                result:
                  type: object
              required: [jobId, status, result]
      responses:
        '200':
          description: Ergebnis wurde angenommen

  /register:
    post:
      summary: Registering a new worker daemon
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                workerId:
                  type: string
                cpu:
                  type: string
                ram:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Erfolgreich registriert

        '400':
          description: Ungültige Eingabedaten