# This is a Docker Compose file for the User Management service.
services:
  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green-load-shifting-platform
    ports:
      - "8080:8080"
    environment:
      USE_LIVE: "true"
      AUTH0_TOKEN_URL: "https://dev-jqhwcu7xuwgdqi56.eu.auth0.com/oauth/token"
      JWT_AUDIENCE: "https://green-load-shifting-platform/"
      ADMIN_SECRET_HASH: "da359894a57a42c65efa8b98c8c86f3f974ff2c8dd7fc428fd87ce6ecdc40bd7"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge