version: "3.9"

services:
  user-management:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: user-management
    ports:
      - "8081:8081"
    environment:
      - JWKS_URL=${JWKS_URL}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - ADMIN_SECRET=${ADMIN_SECRET}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
