openapi: 3.0.0
info:
  title: Job Scheduler API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Ping the server
      responses:
        200:
          description: Returns a pong response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleResponse"
  /schedule:
    post:
      summary: Schedule a job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleRequest"
      responses:
        200:
          description: Job scheduled successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleResponse"
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleResponse"
        401:
          description: "Unauthorized: invalid secret"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleResponse"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleResponse"
components:
  schemas:
    ScheduleRequest:
      type: object
      properties:
        secret:
          type: string
          description: Secret key for authorization
    ScheduleResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message, if any
        message:
          type: string
          description: Response message
