services:
  job-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-scheduler
    environment:
      - WORKER_REGISTRY=http://worker-registry:8080
      - JOB_SERVICE=http://job-service:8080
      - CARBON_INTENSITY_PROVIDER=http://carbon-intensity-provider:8080
      - JOB_SCHEDULER_INTERVAL=5
      - LOG_LEVEL=debug
      - USER_MANAGEMENT_URL=http://user-management:8080
      - AUTH_TOKEN="something to test, will probably need to be adjusted soon"
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - JOB_SCHEDULER_SECRET="Some really secure secret"
    ports:
      - "8080:8080"
