services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318" # OTLP HTTP receiver
      # - "4317:4317"
      # - "5778:5778"
      # - "9411:9411"
