# This is the Docker Compose file for the Conusumer Gateway service
services:
  consumer-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge