openapi: 3.0.3
info:
  title: Job Microservice API
  description: API which handles information of assigned Consumer-Jobs in a Queue
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Job-Microservice
paths:
  /jobs:
    get:
      summary: Get jobs
      description: Retrieve a list of jobs with optional filtering.
      parameters:
        - name: status
          in: query
          required: false
          description: Filter jobs by status
          schema:
            type: string
            enum: [queued, running, completed, failed, cancelled]
        - name: userId
          in: query
          required: false
          description: Filter jobs by user ID
          schema:
            type: string
        - name: priority
          in: query
          required: false
          description: Filter jobs by priority
          schema:
            type: integer
            enum: [0, 1, 2]
        - name: imageId
          in: query
          required: false
          description: Filter jobs by image ID
          schema:
            type: string
      responses:
        200:
          description: A list of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
    post:
      summary: Create a new job
      description: Add a new job to the queue.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobCreate'
      responses:
        201:
          description: Job created successfully
  /jobs/{jobId}:
    get:
      summary: Get a specific job
      description: Retrieve a job by its ID.
      parameters:
        - name: jobId
          in: path
          required: true
          description: The ID of the job to retrieve
          schema:
            type: string
      responses:
        200:
          description: A single job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
    put:
      summary: Update a job
      description: Update an existing job identified by its ID.
      parameters:
        - name: jobId
          in: path
          required: true
          description: The ID of the job to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobUpdate'
      responses:
        200:
          description: Job updated successfully
    delete:
      summary: Delete a job
      description: Delete a job identified by its ID.
      parameters:
        - name: jobId
          in: path
          required: true
          description: The ID of the job to delete
          schema:
            type: string
      responses:
        204:
          description: Job deleted successfully
  /jobs/{jobId}/workerId:
    patch:
      summary: Update worker ID
      description: Update the worker ID of a job identified by its ID.
      parameters:
        - name: jobId
          in: path
          required: true
          description: The ID of the job to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                workerId:
                  type: string
      responses:
        200:
          description: Worker ID updated successfully
  /jobs/{jobId}/status:
    patch:
      summary: Update job status
      description: Update the status of a job identified by its ID.
      parameters:
        - name: jobId
          in: path
          required: true
          description: The ID of the job to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [queued, running, completed, failed, cancelled]
      responses:
        200:
          description: Job status updated successfully
components:
  schemas:
    Job:
      type: object
      properties:
        jobId:
          type: string
        jobName:
          type: string
        userId:
          type: string
        image:
          $ref: '#/components/schemas/ContainerImage'
        parameters:
          type: array
          items:
            type: string
        priority:
          type: integer
          enum: [0, 1, 2]
        status:
          type: string
          enum: [queued, running, completed, failed, cancelled]
        createdAt:
          type: string
          format: date-time
        workerId:
          type: string
          nullable: true
        errorMessage:
          type: string
          nullable: true
        computeLocation:
          type: string
          nullable: true
        carbonItensity:
          type: integer
          nullable: true
        constraints:
          $ref: '#/components/schemas/JobConstraints'
        result:
          type: string
          nullable: true
        maxRetries:
          type: integer
        startedAt:
          type: string
          format: date-time
          nullable: true
        completedAt:
          type: string
          format: date-time
          nullable: true
        lastUpdatedAt:
          type: string
          format: date-time
    JobCreate:
      type: object
      required:
        - userId
        - image
        - parameters
        - priority
      properties:
        userId:
          type: string
        image:
          $ref: '#/components/schemas/ContainerImage'
        parameters:
          type: array
          items:
            type: string
        priority:
          type: integer
          enum: [0, 1, 2]
    JobUpdate:
      type: object
      properties:
        image:
          $ref: '#/components/schemas/ContainerImage'
        parameters:
          type: array
          items:
            type: string
        priority:
          type: integer
          enum: [0, 1, 2]
    JobConstraints:
      type: object
      properties:
        maxRuntime:
          type: integer
        preferredLocation:
          type: array
          items:
            type: string
    ContainerImage:
      type: object
      properties:
        imageId:
          type: string
        imageName:
          type: string
        imageVersion:
          type: string