version: "3.9"

services:
  jobservice:
    build: .
    container_name: jobservice
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - JOB_REPO_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=jobuser
      - DB_PASSWORD=jobpass
      - DB_NAME=jobdb
      - SSL_MODE=false
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://jaeger:4318/"
      - LOG_LEVEL=debug
    depends_on:
      - postgres
    networks:
      - jobnet

  postgres:
    image: postgres:latest
    container_name: job-postgres
    environment:
      - POSTGRES_USER=jobuser
      - POSTGRES_PASSWORD=jobpass
      - POSTGRES_DB=jobdb
    volumes:
      - /home/cyberdefending/Schreibtisch/cmg_test_volumeplace:/var/lib/postgresql/data
      - ../../database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - jobnet

networks:
  jobnet:
    driver: bridge