@startuml
actor "User"


== Create Job ==
User -> CLI: create job <image-id>
CLI -> "Consumer Gateway": POST\n/jobs <image-id, {token}>
note right of CLI: token was issued\nduring Login
note over "Consumer Gateway": creates job-id\nfor job
"Consumer Gateway" -> Job: POST\n/jobs  <image-id, {token}, job-id>


== Schedule Job ==
note over Job: Job scheduling happens here ... 

== Create Job: Feedback to User ==
"Consumer Gateway" -> "Job": GET\n/job/status <job-id, image-id,{token}>
"CLI" -> "Consumer Gateway": GET\n/job/status <image-id, job-id>
"User" -> "CLI": GET\n/job/status <image-id, job-id>

@enduml