openapi: 3.0.3
info:
  title: carbon-intensity-provider Service API
  description: API for getting and putting carbonIntensityProviders that consist of an id, an integer, and a string.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /carbon-intensity-provider/{id}:
    get:
      summary: Get an carbon-intensity-provider by ID
      tags:
        - carbon-intensity-provider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: carbon-intensity-provider details
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                    description: the id of the carbon-intensity-provider
                  IntProp:
                    type: integer
                    description: an integer property
                  StringProp:
                    type: string
                    description: a string property
        '404':
          description: carbon-intensity-provider not found  
  /carbon-intensity-provider:
    put:
      summary: Update/Create an carbon-intensity-provider by ID
      tags:
        - carbon-intensity-provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Id:
                  type: string
                  description: the id of the carbon-intensity-provider
                IntProp:
                  type: integer
                  description: an integer property
                StringProp:
                  type: string
                  description: a string property
      responses:
        '200':
          description: carbon-intensity-provider updated
