services:
  carbon-intensity-provider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbon-intensity-provider
    ports:
      - "8080:8080"
    environment:
      - USE_LIVE=false
      - TOKEN_GB=QNk1Rdt3g3GGEnbPCROu
      - TOKEN_DE=MSUX5RJxZtdO2avdqoXY
    volumes:
      - ./zones.json:/app/zones.json
      - ./zones_metadata.json:/app/zones_metadata.json
    restart: unless-stopped