services:
  carbon-intensity-provider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbon-intensity-provider
    ports:
      - "8080:8080"
    environment:
      - USE_LIVE=false
      # If necessary, set the following environment variables
      # - CARBON_INTENSITY_API_KEY=your_api_key
    restart: unless-stopped